using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;

namespace FileDentify
{
    internal static partial class FileInspector
    {        internal static string BuildReportText(FileReport report)
        {
            var sb = new StringBuilder();
            sb.AppendLine(report.DisplayName);
            sb.AppendLine(new string('=', report.DisplayName.Length));
            foreach (var section in report.Sections)
            {
                sb.AppendLine();
                sb.AppendLine(section.Title);
                sb.AppendLine(new string('-', section.Title.Length));
                foreach (var item in section.Items)
                {
                    var detail = ReportSection.NormalizeDetailText(item.Detail);
                    if (string.Equals((item.Title ?? string.Empty).Trim(), detail.Trim(), StringComparison.Ordinal))
                    {
                        sb.AppendLine(item.Title);
                    }
                    else
                    {
                        sb.AppendLine(item.Title + ":");
                        sb.AppendLine(detail);
                    }
                }
            }
            return sb.ToString().TrimEnd();
        }

        internal static string BuildCombinedText(IEnumerable<FileReport> reports)
        {
            return BuildCombinedText(reports, null);
        }

        internal static string BuildCombinedText(IEnumerable<FileReport> reports, TimeSpan? elapsed)
        {
            var reportList = reports.ToList();
            var sb = new StringBuilder();
            if (reportList.Count > 1)
            {
                AppendTextOverview(sb, reportList, elapsed);
                sb.AppendLine();
            }
            foreach (var report in reportList)
            {
                sb.AppendLine(report.FullText ?? BuildReportText(report));
                sb.AppendLine();
            }
            return sb.ToString().TrimEnd();
        }

        internal static string BuildOverviewText(IEnumerable<FileReport> reports, TimeSpan? elapsed)
        {
            var reportList = reports.ToList();
            if (reportList.Count <= 1)
                return string.Empty;
            var sb = new StringBuilder();
            AppendTextOverview(sb, reportList, elapsed);
            return sb.ToString().TrimEnd();
        }

        internal static string BuildCombinedHtml(IEnumerable<FileReport> reports, string title)
        {
            return BuildCombinedHtml(reports, title, null);
        }

        internal static string BuildCombinedHtml(IEnumerable<FileReport> reports, string title, TimeSpan? elapsed)
        {
            var reportList = reports.ToList();
            var sb = new StringBuilder();
            sb.AppendLine("<!doctype html>");
            sb.AppendLine("<html lang=\"en\">");
            sb.AppendLine("<head>");
            sb.AppendLine("<meta charset=\"utf-8\">");
            sb.AppendLine("<title>" + Html(title) + "</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;line-height:1.45;margin:2rem;max-width:110rem;color:#111;background:#fff}");
            sb.AppendLine("h1,h2,h3{line-height:1.2}");
            sb.AppendLine("nav ul{columns:2;max-width:70rem}");
            sb.AppendLine("table{border-collapse:collapse;width:100%;margin:0.75rem 0 2rem}");
            sb.AppendLine("th,td{border:1px solid #bbb;padding:0.35rem 0.5rem;text-align:left;vertical-align:top}");
            sb.AppendLine("th{background:#f0f0f0}");
            sb.AppendLine("td:first-child{width:18rem;font-weight:600}");
            sb.AppendLine("pre{white-space:pre-wrap;margin:0;font-family:Consolas,monospace}");
            sb.AppendLine(".meta{margin-bottom:1.5rem}");
            sb.AppendLine("</style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine("<h1>" + Html(title) + "</h1>");
            sb.AppendLine("<p class=\"meta\">Generated by FileDentify " + Html(Program.Version) + " on " + Html(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)) + ". This is one combined report containing " + reportList.Count.ToString(CultureInfo.InvariantCulture) + " file" + (reportList.Count == 1 ? string.Empty : "s") + ".</p>");
            if (reportList.Count > 1)
            {
                AppendHtmlOverview(sb, reportList, elapsed);
                sb.AppendLine("<nav aria-label=\"Files in this report\">");
                sb.AppendLine("<h2>Files</h2>");
                sb.AppendLine("<ul>");
                for (var i = 0; i < reportList.Count; i++)
                    sb.AppendLine("<li><a href=\"#file-" + i.ToString(CultureInfo.InvariantCulture) + "\">" + Html(reportList[i].DisplayName) + "</a></li>");
                sb.AppendLine("</ul>");
                sb.AppendLine("</nav>");
            }

            for (var i = 0; i < reportList.Count; i++)
            {
                var report = reportList[i];
                sb.AppendLine("<article id=\"file-" + i.ToString(CultureInfo.InvariantCulture) + "\">");
                sb.AppendLine("<h2>" + Html(report.DisplayName) + "</h2>");
                foreach (var section in report.Sections)
                {
                    sb.AppendLine("<section>");
                    sb.AppendLine("<h3>" + Html(section.Title) + "</h3>");
                    sb.AppendLine("<table>");
                    sb.AppendLine("<thead><tr><th scope=\"col\">Item</th><th scope=\"col\">Details</th></tr></thead>");
                    sb.AppendLine("<tbody>");
                    foreach (var item in section.Items)
                    {
                        var detail = ReportSection.NormalizeDetailText(item.Detail);
                        if (string.Equals((item.Title ?? string.Empty).Trim(), detail.Trim(), StringComparison.Ordinal))
                            sb.AppendLine("<tr><td colspan=\"2\"><pre>" + Html(detail) + "</pre></td></tr>");
                        else
                            sb.AppendLine("<tr><td>" + Html(item.Title) + "</td><td><pre>" + Html(detail) + "</pre></td></tr>");
                    }
                    sb.AppendLine("</tbody>");
                    sb.AppendLine("</table>");
                    sb.AppendLine("</section>");
                }
                sb.AppendLine("</article>");
            }
            sb.AppendLine("</body>");
            sb.AppendLine("</html>");
            return sb.ToString();
        }

        private static void AppendTextOverview(StringBuilder sb, List<FileReport> reports, TimeSpan? elapsed)
        {
            var rows = BuildOverviewRows(reports);
            sb.AppendLine("Report overview");
            sb.AppendLine("===============");
            sb.AppendLine("Files:");
            sb.AppendLine(reports.Count.ToString(CultureInfo.InvariantCulture));
            if (elapsed.HasValue)
            {
                sb.AppendLine("Generation time:");
                sb.AppendLine(FormatElapsed(elapsed.Value));
            }
            sb.AppendLine("Total reported size:");
            sb.AppendLine(FormatBytes(rows.Sum(r => r.SizeBytes)));
            sb.AppendLine("Unknown type files:");
            sb.AppendLine(rows.Count(r => r.IsUnknown).ToString(CultureInfo.InvariantCulture));
            sb.AppendLine("Inspection errors:");
            sb.AppendLine(rows.Count(r => r.HasError).ToString(CultureInfo.InvariantCulture));
            sb.AppendLine("Files without a built-in signature match:");
            sb.AppendLine(rows.Count(r => r.NoSignatureMatch).ToString(CultureInfo.InvariantCulture));

            sb.AppendLine();
            sb.AppendLine("Likely types");
            sb.AppendLine("------------");
            foreach (var group in rows.GroupBy(r => r.LikelyType).OrderByDescending(g => g.Count()).ThenBy(g => g.Key).Take(25))
                sb.AppendLine(group.Count().ToString(CultureInfo.InvariantCulture) + " - " + group.Key);

            sb.AppendLine();
            sb.AppendLine("Extensions");
            sb.AppendLine("----------");
            foreach (var group in rows.GroupBy(r => string.IsNullOrWhiteSpace(r.Extension) ? "(none)" : r.Extension).OrderByDescending(g => g.Count()).ThenBy(g => g.Key).Take(25))
                sb.AppendLine(group.Count().ToString(CultureInfo.InvariantCulture) + " - " + group.Key);

            sb.AppendLine();
            sb.AppendLine("Largest files");
            sb.AppendLine("-------------");
            foreach (var row in rows.OrderByDescending(r => r.SizeBytes).Take(15))
                sb.AppendLine(FormatBytes(row.SizeBytes) + " - " + row.DisplayName + " - " + row.Path);

            var commonBytes = CommonBytes(rows).Take(16).ToArray();
            if (commonBytes.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Most common sampled bytes across files");
                sb.AppendLine("--------------------------------------");
                foreach (var item in commonBytes)
                    sb.AppendLine("0x" + item.ByteValue.ToString("X2", CultureInfo.InvariantCulture) + " - " + item.Count.ToString(CultureInfo.InvariantCulture));
            }

            var commonStrings = CommonReadableStrings(rows).Take(30).ToArray();
            if (commonStrings.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Common readable strings");
                sb.AppendLine("-----------------------");
                foreach (var item in commonStrings)
                    sb.AppendLine(item.FileCount.ToString(CultureInfo.InvariantCulture) + " files - " + item.Value);
            }

            var attention = rows.Where(r => r.IsUnknown || r.HasError).Take(50).ToArray();
            if (attention.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Needs attention");
                sb.AppendLine("---------------");
                foreach (var row in attention)
                    sb.AppendLine(row.DisplayName + " - " + row.LikelyType + " - " + row.Path);
            }
        }

        private static void AppendHtmlOverview(StringBuilder sb, List<FileReport> reports, TimeSpan? elapsed)
        {
            var rows = BuildOverviewRows(reports);
            sb.AppendLine("<section id=\"overview\">");
            sb.AppendLine("<h2>Report overview</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");
            HtmlMetric(sb, "Files", reports.Count.ToString(CultureInfo.InvariantCulture));
            if (elapsed.HasValue)
                HtmlMetric(sb, "Generation time", FormatElapsed(elapsed.Value));
            HtmlMetric(sb, "Total reported size", FormatBytes(rows.Sum(r => r.SizeBytes)));
            HtmlMetric(sb, "Unknown type files", rows.Count(r => r.IsUnknown).ToString(CultureInfo.InvariantCulture));
            HtmlMetric(sb, "Inspection errors", rows.Count(r => r.HasError).ToString(CultureInfo.InvariantCulture));
            HtmlMetric(sb, "Files without a built-in signature match", rows.Count(r => r.NoSignatureMatch).ToString(CultureInfo.InvariantCulture));
            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h3>Likely types</h3>");
            sb.AppendLine("<table><thead><tr><th scope=\"col\">Count</th><th scope=\"col\">Likely type</th></tr></thead><tbody>");
            foreach (var group in rows.GroupBy(r => r.LikelyType).OrderByDescending(g => g.Count()).ThenBy(g => g.Key).Take(50))
                sb.AppendLine("<tr><td>" + group.Count().ToString(CultureInfo.InvariantCulture) + "</td><td>" + Html(group.Key) + "</td></tr>");
            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<h3>Extensions</h3>");
            sb.AppendLine("<table><thead><tr><th scope=\"col\">Count</th><th scope=\"col\">Extension</th></tr></thead><tbody>");
            foreach (var group in rows.GroupBy(r => string.IsNullOrWhiteSpace(r.Extension) ? "(none)" : r.Extension).OrderByDescending(g => g.Count()).ThenBy(g => g.Key).Take(50))
                sb.AppendLine("<tr><td>" + group.Count().ToString(CultureInfo.InvariantCulture) + "</td><td>" + Html(group.Key) + "</td></tr>");
            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<h3>Largest files</h3>");
            sb.AppendLine("<table><thead><tr><th scope=\"col\">Size</th><th scope=\"col\">File</th><th scope=\"col\">Path</th></tr></thead><tbody>");
            foreach (var row in rows.OrderByDescending(r => r.SizeBytes).Take(25))
                sb.AppendLine("<tr><td>" + Html(FormatBytes(row.SizeBytes)) + "</td><td>" + Html(row.DisplayName) + "</td><td>" + Html(row.Path) + "</td></tr>");
            sb.AppendLine("</tbody></table>");

            var commonBytes = CommonBytes(rows).Take(16).ToArray();
            if (commonBytes.Length > 0)
            {
                sb.AppendLine("<h3>Most common sampled bytes across files</h3>");
                sb.AppendLine("<table><thead><tr><th scope=\"col\">Byte</th><th scope=\"col\">Sample count</th></tr></thead><tbody>");
                foreach (var item in commonBytes)
                    sb.AppendLine("<tr><td>0x" + item.ByteValue.ToString("X2", CultureInfo.InvariantCulture) + "</td><td>" + item.Count.ToString(CultureInfo.InvariantCulture) + "</td></tr>");
                sb.AppendLine("</tbody></table>");
            }

            var commonStrings = CommonReadableStrings(rows).Take(50).ToArray();
            if (commonStrings.Length > 0)
            {
                sb.AppendLine("<h3>Common readable strings</h3>");
                sb.AppendLine("<table><thead><tr><th scope=\"col\">Files</th><th scope=\"col\">String</th></tr></thead><tbody>");
                foreach (var item in commonStrings)
                    sb.AppendLine("<tr><td>" + item.FileCount.ToString(CultureInfo.InvariantCulture) + "</td><td>" + Html(item.Value) + "</td></tr>");
                sb.AppendLine("</tbody></table>");
            }

            var attention = rows.Where(r => r.IsUnknown || r.HasError).Take(100).ToArray();
            if (attention.Length > 0)
            {
                sb.AppendLine("<h3>Needs attention</h3>");
                sb.AppendLine("<table><thead><tr><th scope=\"col\">File</th><th scope=\"col\">Likely type</th><th scope=\"col\">Path</th></tr></thead><tbody>");
                foreach (var row in attention)
                    sb.AppendLine("<tr><td>" + Html(row.DisplayName) + "</td><td>" + Html(row.LikelyType) + "</td><td>" + Html(row.Path) + "</td></tr>");
                sb.AppendLine("</tbody></table>");
            }
            sb.AppendLine("</section>");
        }

        private static void HtmlMetric(StringBuilder sb, string name, string value)
        {
            sb.AppendLine("<tr><td>" + Html(name) + "</td><td>" + Html(value) + "</td></tr>");
        }

        private static List<ReportOverviewRow> BuildOverviewRows(IEnumerable<FileReport> reports)
        {
            var rows = new List<ReportOverviewRow>();
            foreach (var report in reports)
            {
                var row = new ReportOverviewRow();
                row.DisplayName = report.DisplayName ?? string.Empty;
                row.LikelyType = FindReportValue(report, "Summary", "Likely type");
                if (string.IsNullOrWhiteSpace(row.LikelyType))
                    row.LikelyType = HasSection(report, "Inspection error") ? "Inspection error" : "(not reported)";
                row.Path = FindReportValue(report, "Summary", "Path");
                if (string.IsNullOrWhiteSpace(row.Path))
                    row.Path = FindReportValue(report, "Inspection error", "Path");
                row.Extension = FindReportValue(report, "Summary", "Extension");
                row.SizeBytes = ParseSizeBytes(FindReportValue(report, "Summary", "Size"));
                row.HasError = HasSection(report, "Inspection error");
                row.IsUnknown = row.LikelyType.IndexOf("Unknown binary data", StringComparison.OrdinalIgnoreCase) >= 0;
                row.NoSignatureMatch = HasItem(report, "Signature matches", "No common signature match");
                row.ByteCounts = ParseByteCounts(FindReportValue(report, "Byte statistics", "Most common bytes"));
                row.ReadableStrings = ReadableStrings(report);
                rows.Add(row);
            }
            return rows;
        }

        private static long ParseSizeBytes(string sizeText)
        {
            if (string.IsNullOrWhiteSpace(sizeText))
                return 0;
            var match = Regex.Match(sizeText, @"\(([\d,]+) bytes\)");
            if (!match.Success)
                return 0;
            long value;
            return long.TryParse(match.Groups[1].Value.Replace(",", string.Empty), NumberStyles.Integer, CultureInfo.InvariantCulture, out value) ? value : 0;
        }

        private static Dictionary<byte, int> ParseByteCounts(string text)
        {
            var counts = new Dictionary<byte, int>();
            if (string.IsNullOrWhiteSpace(text))
                return counts;
            foreach (var line in text.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
            {
                var match = Regex.Match(line.Trim(), @"^0x([0-9A-Fa-f]{2})\s+(\d+)$");
                if (!match.Success)
                    continue;
                byte byteValue;
                int count;
                if (byte.TryParse(match.Groups[1].Value, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out byteValue) &&
                    int.TryParse(match.Groups[2].Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out count))
                    counts[byteValue] = count;
            }
            return counts;
        }

        private static List<string> ReadableStrings(FileReport report)
        {
            var section = report.Sections.FirstOrDefault(s => string.Equals(s.Title, "Readable text", StringComparison.OrdinalIgnoreCase));
            if (section == null)
                return new List<string>();
            return section.Items
                .Where(i => !string.Equals(i.Title, "Scan note", StringComparison.OrdinalIgnoreCase) &&
                    !string.Equals(i.Title, "Limit", StringComparison.OrdinalIgnoreCase) &&
                    !string.Equals(i.Title, "No readable text found", StringComparison.OrdinalIgnoreCase))
                .Select(i => (i.Detail ?? i.Title ?? string.Empty).Trim())
                .Where(s => s.Length >= 4 && s.Length <= 180)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private static IEnumerable<CommonByteRow> CommonBytes(IEnumerable<ReportOverviewRow> rows)
        {
            var totals = new Dictionary<byte, int>();
            foreach (var row in rows)
                foreach (var pair in row.ByteCounts)
                    totals[pair.Key] = totals.ContainsKey(pair.Key) ? totals[pair.Key] + pair.Value : pair.Value;
            return totals.Select(p => new CommonByteRow { ByteValue = p.Key, Count = p.Value }).OrderByDescending(r => r.Count).ThenBy(r => r.ByteValue);
        }

        private static IEnumerable<CommonStringRow> CommonReadableStrings(IEnumerable<ReportOverviewRow> rows)
        {
            return rows
                .SelectMany(r => r.ReadableStrings.Select(s => new { r.DisplayName, Value = s }))
                .GroupBy(x => x.Value, StringComparer.OrdinalIgnoreCase)
                .Select(g => new CommonStringRow { Value = g.First().Value, FileCount = g.Select(x => x.DisplayName).Distinct(StringComparer.OrdinalIgnoreCase).Count() })
                .Where(r => r.FileCount >= 2)
                .OrderByDescending(r => r.FileCount)
                .ThenBy(r => r.Value);
        }

        private static string FormatElapsed(TimeSpan elapsed)
        {
            return elapsed.TotalSeconds < 60
                ? elapsed.TotalSeconds.ToString("0.0", CultureInfo.InvariantCulture) + " seconds"
                : elapsed.ToString(@"hh\:mm\:ss", CultureInfo.InvariantCulture);
        }

        private static string FindReportValue(FileReport report, string sectionTitle, string itemTitle)
        {
            var section = report.Sections.FirstOrDefault(s => string.Equals(s.Title, sectionTitle, StringComparison.OrdinalIgnoreCase));
            if (section == null)
                return string.Empty;
            var item = section.Items.FirstOrDefault(i => string.Equals(i.Title, itemTitle, StringComparison.OrdinalIgnoreCase));
            return item == null ? string.Empty : item.Detail ?? string.Empty;
        }

        private static bool HasSection(FileReport report, string sectionTitle)
        {
            return report.Sections.Any(s => string.Equals(s.Title, sectionTitle, StringComparison.OrdinalIgnoreCase));
        }

        private static bool HasItem(FileReport report, string sectionTitle, string itemTitle)
        {
            var section = report.Sections.FirstOrDefault(s => string.Equals(s.Title, sectionTitle, StringComparison.OrdinalIgnoreCase));
            return section != null && section.Items.Any(i => string.Equals(i.Title, itemTitle, StringComparison.OrdinalIgnoreCase));
        }

        private sealed class ReportOverviewRow
        {
            public string DisplayName;
            public string LikelyType;
            public string Path;
            public string Extension;
            public long SizeBytes;
            public bool HasError;
            public bool IsUnknown;
            public bool NoSignatureMatch;
            public Dictionary<byte, int> ByteCounts = new Dictionary<byte, int>();
            public List<string> ReadableStrings = new List<string>();
        }

        private sealed class CommonByteRow
        {
            public byte ByteValue;
            public int Count;
        }

        private sealed class CommonStringRow
        {
            public string Value;
            public int FileCount;
        }

        internal static FileReport BuildErrorReport(string path, Exception ex)
        {
            var report = new FileReport();
            report.DisplayName = Path.GetFileName(path);
            report.OriginalPath = path;
            var section = AddSection(report.Sections, "Inspection error");
            Add(section, "Path", path);
            Add(section, "Error", ex.Message);
            report.FullText = BuildReportText(report);
            return report;
        }

        private static string Html(string value)
        {
            return WebUtility.HtmlEncode(value ?? string.Empty);
        }
    }
}

