using System.Text;

namespace FileDentify
{
    internal static partial class ManualService
    {
        private static void Changelog(StringBuilder html)
        {
            html.AppendLine("<h2 id=\"changelog\">Changelog</h2>");
            html.AppendLine("<h3>1.7</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Added clearer SQLite-family handling for <code>.sqlite</code>, <code>.sqlite3</code>, <code>.db</code>, and <code>.db3</code> files, including safer mismatch logic so valid <code>.db3</code> databases are not flagged as suspicious.</li>");
            html.AppendLine("<li>Added browser/profile support for Thunderbird <code>.wdseml</code> snippets and <code>.msf</code> indexes, Firefox/Thunderbird <code>.jsonlz4</code> profile data, and SQLite sidecar files.</li>");
            html.AppendLine("<li>Expanded music-production, browser/profile, scientific, system, and developer-resource coverage from a fresh large-folder scan, including Ableton <code>.asd</code> analysis sidecars, Logic <code>.undo</code> sidecars, REAPER theme packages, Plugin Alliance bundles, Vital presets/banks, TensorFlow Lite and ONNX Runtime model files, extra Spectrasonics database/map files, Firebird databases, FITS scientific data, ICC profiles, Embedded OpenType fonts, Windows minidumps, Chromium Safe Browsing stores, Debian packages, FBX models, Tcl encoding maps, and more source/build resource formats. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Refined Steinberg/VST reporting so Windows plug-in DLLs with Steinberg VST SDK strings are reported as plug-ins, not as Cubase projects, and tightened readable-text filtering for binary fragments in executable headers.</li>");
            html.AppendLine("<li>Added Mercury/32 and Pegasus Mail support-file reporting from an old server-backup audit, covering rule files, mailing-list files, mailbox cache/index/state sidecars, content-control sets, form fact files, and sample configuration files while avoiding address/member/body summaries in the special section.</li>");
            html.AppendLine("<li>Added a scan-filtering workflow for large local folders and used it for a first Windows/program-folder coverage pass, adding Windows MUI/MUN resources, ETL/WER diagnostics, WMI/PowerShell support files, WinRT/XAML/resource files, font collections, device metadata, provisioning files, and common developer/script resources. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Added another uncommon-extension pass covering M3U/M3U8 playlists, HTML Help contents files, old JAWS support files, ModelTalker and Acapela/Infovox speech assets, VLC skin catalogs, antivirus IDE signatures, AppCache manifests, BeebEm/Torch MCP files, and Stylus RMX Korg controller scenes. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Improved readable-text extraction for older high-bit ASCII files, so text stored with the top bit set is surfaced cleanly and short tail fragments are less likely to appear as separate misleading lines.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.6</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Expanded the FileDentify built-in file-type database from a fresh local software-library scan, with extra attention on extensionless files and older music/game/support formats. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Added Roland Fantom Librarian reporting for <code>.fxl</code> and <code>.fsl</code> files, including Fantom-S/Fantom-X markers, target family, file role, and visible patch or library names where present.</li>");
            html.AppendLine("<li>Added Yamaha S-YXG software-synthesizer table reporting for older Yamaha softsynth <code>.tbl</code> files, with separate handling so unrelated <code>.tbl</code> files are not mislabeled.</li>");
            html.AppendLine("<li>Added OpenAL spatial-audio reporting for <code>.mhr</code> HRTF data and <code>.ambdec</code> ambisonic decoder presets, including header/configuration clues and filename sample-rate hints where available.</li>");
            html.AppendLine("<li>Added BBC Micro / BeebEm media reporting for <code>.ssd</code>, <code>.uef</code>, and PHROM-style extensionless emulator files.</li>");
            html.AppendLine("<li>Added header-based handling for same-extension <code>.pat</code> collisions, distinguishing Gravis UltraSound GF1 instrument patches from Synology DSM/SRM update packages.</li>");
            html.AppendLine("<li>Added production-audio resource reporting from a refreshed production-library scan, covering Reason NN-XT, classic Logic, GarageBand chord data, Native Instruments sample-add files, MAGIX/SEK'D sidecars, Akai sampler programs/multis, ReBirth mods, and GN Audio MIDI containers.</li>");
            html.AppendLine("<li>Added Chromium hyphenation dictionaries, LibreOffice/OpenOffice support resources, and Winamp 5/Wasabi plug-in modules to the app-resource coverage.</li>");
            html.AppendLine("<li>Added another candidate-list pass for common but easy-to-overlook support formats, including dictionaries, RTF, Jet/Access databases, COM type libraries, Windows Media/ASF containers, and Type 1 font support files. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Added real-world TV/music archive candidates including Sound Designer II audio, Cool Edit / Adobe Audition sessions, Windows Media Player playlists, raw MPEG audio streams, extensionless ID3-tagged MP3s, and Barrcode AA audio-resource markers.</li>");
            html.AppendLine("<li>Added a FileDentify database section near the top of reports when FileDentify's own built-in rules identify the file, making it clearer when the answer comes from FileDentify rather than Unix file/libmagic or generic signatures.</li>");
            html.AppendLine("<li>Expanded Native Instruments reporting from a full Komplete library audit, including clearer product and role hints for Kontakt, Battery, Reaktor, Maschine, Guitar Rig, Komplete Kontrol, and related preset, snapshot, ensemble, resource, and extensionless files.</li>");
            html.AppendLine("<li>Audited format notes across the newer FileDentify-specific sections so obscure formats explain their likely product, platform, or purpose without implying that FileDentify decodes proprietary payloads.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.5</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Expanded real-world audio-library and macOS-resource coverage from local sample-library, plug-in, application-support, and system-library scans. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Added richer reporting for VST3 module metadata, including module name, vendor, class/category, subcategory, class ID, and version fields where <code>moduleinfo.json</code> is present.</li>");
            html.AppendLine("<li>Added focused audio-resource reporting for Arturia, ROLI, Initial Audio, Guitar Rig impulse-response, Apple Core Audio/Space Designer, Scala tuning, and wavetable files, with context and visible metadata where available.</li>");
            html.AppendLine("<li>Send To now appends plain file and folder inputs to an already running FileDentify window instead of replacing the current report. Use File &gt; New report or <code>Ctrl+N</code> when you explicitly want to start over.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.4.1</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Media reports now surface high-value sections such as Windows property metadata, QuickTime metadata, ISO base media, Media details, and ffprobe output closer to the top of each file report.</li>");
            html.AppendLine("<li>Improved old memory-card reports with clearer ScanSoft RealSpeak Mobile speech headers, Symbian thumbnail/mask sidecars, Roland FA sample/song section priority, and Nintendo flashcart save clues.</li>");
            html.AppendLine("<li>Expanded macOS application-bundle coverage for XPC services, compiled storyboard and Core Data resource folders, RTFD documents, Metal shader libraries, scripting definitions, entitlements, and privacy manifests.</li>");
            html.AppendLine("<li>Embedded runtime extraction now uses one FileDentify temp root per running process and removes stale FileDentify temp folders on launch and exit.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.4</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Fixed last-report recovery so closing FileDentify with <code>Escape</code> saves the currently selected file, section, and report item before exit.</li>");
            html.AppendLine("<li>Fixed locked or unreadable files, such as a live Windows <code>NTUSER.DAT</code>, so they appear as inspection-error entries instead of stopping the GUI report run.</li>");
            html.AppendLine("<li>Added cautious identification for protected <code>.bpak</code> game packages, including fruit-machine or digital slot-machine package filename clues.</li>");
            html.AppendLine("<li>Added more classic game detail for Quake-family files, including BSP maps, demo recordings, QuakeC <code>progs.dat</code>, models, and sprites, plus Duke Nukem 3D saved-game context.</li>");
            html.AppendLine("<li>Added Quick Windows Sequencer (QWS) support-file reporting for instrument maps, note transforms, language prompts, and settings files while avoiding printing recent-file paths from QWS settings.</li>");
            html.AppendLine("<li>Added NVDA add-on package reporting for <code>.nvda-addon</code> files, including manifest metadata and package structure counts.</li>");
            html.AppendLine("<li>Expanded reporting for firmware, hardware-ID databases, VMware metadata, Electron ASAR archives, NuGet packages, AI model files, speech-engine data, and other large or confusing system/support files. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Added personal/export reporting for Nokia/Symbian messages, vCard contacts, iCalendar files, OPML subscription lists, EML messages, and Windows Media Encoder session files.</li>");
            html.AppendLine("<li>Added Windows/system reporting for event logs, driver setup caches, printer descriptions, licensing XML, compatibility databases, catalog databases, AppX/MSIX packages, translation catalogs, network config files, and application manifests.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.3</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Added configurable report-section ordering from the main tree. Use <code>Ctrl+Up</code> and <code>Ctrl+Down</code> on a report section to move it earlier or later. <code>Summary</code> stays pinned first, and file order stays natural.</li>");
            html.AppendLine("<li>Added Sensor Readout-style section navigation. <code>Ctrl+0</code> through <code>Ctrl+9</code> jump through the current file's first ten sections, <code>Ctrl+Shift+0</code> through <code>Ctrl+Shift+9</code> jump through sections 10 to 19, <code>Alt+Up</code> / <code>Alt+Down</code> move to the previous or next section, and <code>Alt+Home</code> / <code>Alt+End</code> jump to the first or last section without leaving the details field.</li>");
            html.AppendLine("<li>Added file navigation shortcuts for multi-file reports. <code>Alt+Left</code> and <code>Alt+Right</code> jump to the previous or next file, <code>Alt+PageUp</code> and <code>Alt+PageDown</code> jump to the first or last file, <code>Alt+Backspace</code> jumps to Report overview, and <code>Alt+1</code> through <code>Alt+0</code> jump directly to files 1 through 10. File navigation keeps the same report section selected when that section exists in the destination file, otherwise it falls back to Summary.</li>");
            html.AppendLine("<li>Added <code>Ctrl+Shift+O</code> to append files to the current report. <code>Ctrl+O</code> now clearly starts a new report and offers to save the current report first.</li>");
            html.AppendLine("<li>Added File &gt; Open folder with <code>Ctrl+Shift+L</code> to recursively inspect an entire folder from inside FileDentify.</li>");
            html.AppendLine("<li>Added native <code>.fdreport</code> saved reports that reopen inside FileDentify with the tree intact. These reports can be sent to another user for analysis, and FileDentify can optionally register the extension with Windows.</li>");
            html.AppendLine("<li>Added package-folder reporting for macOS-style bundles that Windows exposes as folders, including Logic Pro projects, GarageBand projects, Time Machine sparse bundles, app bundles, framework/loadable bundles, and audio plug-in bundles.</li>");
            html.AppendLine("<li>Added automatic last-report recovery. When enabled, FileDentify keeps a private <code>FileDentify.fdreport</code> recovery file beside the app. Use <code>Ctrl+Shift+T</code> or File &gt; Reopen last report to bring it back, including the selected file, section, and report item where possible.</li>");
            html.AppendLine("<li>Added <code>F5</code> to refresh original files from a live or reopened report. If the original files are not available on the current machine, FileDentify explains why the report cannot be fully refreshed.</li>");
            html.AppendLine("<li>Changed the default section order so high-value FileDentify-specific sections appear immediately after Summary. Safety hints and format-specific sections such as Korg, Toontrack, Decent Sampler, Native Instruments, Clipman, project files, package folders, and media/document details are surfaced before generic evidence such as hashes and raw header bytes. If you explicitly move one of those sections, your saved position for that section is respected.</li>");
            html.AppendLine("<li>Added embedded Tolk screen-reader output, including the NVDA controller client companion DLL, for concise shortcut and section-move announcements when a supported screen reader is running.</li>");
            html.AppendLine("<li>Expanded format-specific identification across music production files, sample libraries, Mac package folders, game/audio assets, archives, firmware, AI model files, documents, and media containers. See <a href=\"#supported-file-types\">Supported file types</a> for the maintained coverage table.</li>");
            html.AppendLine("<li>Added more local-sample-backed coverage from the format-discovery comparison, including macOS Finder <code>.DS_Store</code>, Windows icon <code>.ico</code> resources, Windows bitmap font <code>.fon</code> files, and richer Opus-in-Ogg metadata.</li>");
            html.AppendLine("<li>Improved main-window section details so multiline values stay on separate lines instead of being flattened into very long pipe-separated lines.</li>");
            html.AppendLine("<li>Added safety hints for obvious header and extension mismatches, such as a file with a document, archive, image, shortcut, or executable header but an unexpected extension. FileDentify does not declare malware; it recommends caution and a trusted security scan when the mismatch is suspicious.</li>");
            html.AppendLine("<li>Added command-line output safety checks so report and advanced-viewer output refuse to overwrite one of the input files. Console companion errors now print to stderr instead of opening a GUI error window.</li>");
            html.AppendLine("<li>Added an optional embedded HTML details view in the main window. Press <code>F7</code> or use View &gt; HTML details view to switch between the traditional read-only text details and heading/table-based HTML details. The choice is remembered.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.2</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Added Windows property metadata reporting for formats supported by Explorer property handlers, giving FileDentify another way to surface useful title, author, tag, media, document, and image metadata without bundling a large new parser. Closes <a href=\"https://github.com/OnjLouis/FileDentify/issues/3\">issue 3</a>.</li>");
            html.AppendLine("<li>Added Office Open XML metadata reporting for Word, Excel, and PowerPoint files, including document kind, title, subject, creator, modifier, created/modified dates, keywords, application properties, document counts, embedded/media counts, titles of parts, and custom properties when present.</li>");
            html.AppendLine("<li>Added OpenDocument metadata reporting for files such as <code>.odt</code>, <code>.ods</code>, and <code>.odp</code>, including title, creator, generator, editing details, and document statistics when present.</li>");
            html.AppendLine("<li>Improved likely-type summaries for ZIP-based document formats so common Office and OpenDocument files are identified near the top of the report, not only as generic ZIP-compatible containers.</li>");
            html.AppendLine("<li>Added short command-line switches for every command-line option, including <code>--advanced-view</code> / <code>-av</code> to open the graphical advanced viewer directly on a file.</li>");
            html.AppendLine("<li>Improved the advanced viewer status bar so NVDA's status command can read it. The status now starts with the current line number before the static mode and shortcut text.</li>");
            html.AppendLine("<li>Improved graceful closing so <code>--close</code> / <code>-c</code> can close owned advanced-viewer windows as well as the main FileDentify window.</li>");
            html.AppendLine("<li>Filtered noisy Explorer storage fields from Windows property metadata, including large internal status blobs that are not useful report data.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.1.1</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Fixed an advanced file viewer crash when pressing Enter after searching from a selection at the end of the loaded output.</li>");
            html.AppendLine("<li>Added <code>Ctrl+F</code> in the advanced file viewer to focus the search field and select the previous search text so typing replaces it.</li>");
            html.AppendLine("<li>Added <code>Shift+F3</code> in the advanced file viewer to search backward through loaded output.</li>");
            html.AppendLine("<li>Improved advanced viewer scrolling so loading more data only happens when the review cursor is actually at the loaded end, avoiding confusing line jumps near the end of a loaded block.</li>");
            html.AppendLine("<li>Advanced viewer status now refreshes the current line number while moving through loaded output.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.1</h3>");
            html.AppendLine("<ul>");
            html.AppendLine("<li>Updated embedded Unix file/libmagic to MSYS2 MinGW-w64 file/libmagic 5.48.</li>");
            html.AppendLine("<li>Added PDF Info and XMP metadata reporting, including title, author, creator, producer, creation date, and modification date when present. Closes <a href=\"https://github.com/OnjLouis/FileDentify/issues/1\">issue 1</a>.</li>");
            html.AppendLine("<li>Added multimedia metadata reporting for common audio files, including FLAC duration and Vorbis comments, MP3 ID3v2 tags, MP3 bitrate/sample-rate duration estimates, and concise ffprobe summaries when ffprobe is available. Closes <a href=\"https://github.com/OnjLouis/FileDentify/issues/2\">issue 2</a>.</li>");
            html.AppendLine("<li>Added broad format-specific reporting for DMG, RAR, UFS sample libraries, Clipman .clipdb/settings files, Native Instruments/Kontakt/NKS/Reaktor/Battery/FM8/Absynth/Massive/Maschine/Kontour-related files, Steinberg Cubase/Nuendo/VST files, old mobile phone tones such as iMelody/SMAF/MMF/CMX/PMD, game and ROM files such as NSF/NES/Game Boy/GBA/SNES/Sega/N64/Doom WAD/CHD/Unity/Ren'Py/Wwise/Steam manifests, .blob assets, virtual disks, ISO images, RIFF/IFF, MIDI, SQLite, property lists, fonts, compressed streams, ZIP-compatible containers, and other common structures.</li>");
            html.AppendLine("<li>Added built-in Windows shortcut analysis for <code>.lnk</code> files, including Shell Link flags, target attributes, timestamps, target size, icon index, show command, and hotkey.</li>");
            html.AppendLine("<li>Added built-in Internet Shortcut and saved web favorite analysis for <code>.url</code> files, including modern <code>[InternetShortcut]</code> files and older favorites with <code>BASEURL</code> or <code>ORIGURL</code>.</li>");
            html.AppendLine("<li>Summary now prioritizes FileDentify-specific identifications and keeps long libmagic descriptions in the Unix file/libmagic section.</li>");
            html.AppendLine("<li>Added screen-reader-friendly details behavior: details start at the top, include a trailing blank line, expose shortcut names where Windows supports them, and keep long findings in reviewable text instead of forcing users through dense one-line summaries.</li>");
            html.AppendLine("<li>Added Ctrl+A support in read-only edit fields, scoped Ctrl+C behavior for tree selections and details fields, and a Readable text section for plain strings without byte offsets.</li>");
            html.AppendLine("<li>Added Ctrl+Shift+Left and Ctrl+Shift+Right to collapse or expand the report tree, matching Sensor Readout.</li>");
            html.AppendLine("<li>Added consistent keyboard access: Open files uses Ctrl+O, Save report uses Ctrl+S, Preferences uses Ctrl+comma, View HTML report uses Alt+V, Open containing folder uses Alt+L, and Help uses F1.</li>");
            html.AppendLine("<li>Added an Edit menu, a report-tree context menu, and a main-screen Help button so copy, expand/collapse, save, HTML report, and help actions are discoverable to mouse and keyboard users.</li>");
            html.AppendLine("<li>Added Contact, Donate, and Other software entries to the Help menu, matching the other Andre Louis utilities.</li>");
            html.AppendLine("<li>Added combined HTML report output with headings and section tables. Save report can now write either plain text or HTML, and command-line reports automatically use HTML when the output file ends in <code>.html</code> or <code>.htm</code>.</li>");
            html.AppendLine("<li>Added a Report overview at the top of combined reports, with file counts, generation time, total reported size, likely-type distribution, extension distribution, largest files, common sampled byte values, common readable strings, signature-match counts, and files that need attention.</li>");
            html.AppendLine("<li>Added View HTML report on the main screen. It opens a temporary combined HTML report in the default browser and cleans up the temporary file when FileDentify exits.</li>");
            html.AppendLine("<li>Added <code>--html-report</code> for explicit command-line HTML output.</li>");
            html.AppendLine("<li>Added <code>--folder-report</code> to recursively scan folders into one combined report, either plain text or HTML depending on the output extension.</li>");
            html.AppendLine("<li>Added folder input support in the graphical app and Send To workflow. Folders are recursively expanded into files, progress is shown while files are found and inspected, and empty inputs show a clear no-files message.</li>");
            html.AppendLine("<li>Added a Preferences option to create or remove a FileDentify desktop shortcut.</li>");
            html.AppendLine("<li>Added <code>--close</code> to ask other FileDentify windows from the same executable to close gracefully.</li>");
            html.AppendLine("<li>Added command-line switches for desktop shortcut install/uninstall and update checks.</li>");
            html.AppendLine("<li>Added non-interactive command-line report generation that exits after writing the requested report.</li>");
            html.AppendLine("<li>Added terminal mode through <code>fd.com</code>. Running <code>fd.com [files...]</code> opens terminal paging mode directly. <code>fd.com</code> and <code>FileDentify.exe</code> must live in the same folder.</li>");
            html.AppendLine("<li>Update checks default to startup on new installs, and the updater requires <code>fd.com</code> to be present beside <code>FileDentify.exe</code> in release ZIP files.</li>");
            html.AppendLine("<li>Added this built-in HTML manual on F1.</li>");
            html.AppendLine("<li>Added an advanced file viewer on F4 with readable text, hex, binary, and octal modes, incremental loading, load-all, F3 search, save loaded output, and standard read-only copy/select-all behavior.</li>");
            html.AppendLine("<li>Added command-line advanced viewer output with <code>--viewer-output</code>, <code>--viewer</code>, <code>--viewer-mode</code>, and <code>--viewer-bytes</code>. Terminal mode can also open an in-terminal advanced viewer with F4.</li>");
            html.AppendLine("<li>Updated third-party notices for the embedded MSYS2 file/libmagic runtime dependencies, including libsystre, libtre, gettext/libintl, and libiconv.</li>");
            html.AppendLine("</ul>");
            html.AppendLine("<h3>1.0</h3>");
            html.AppendLine("<ul><li>Initial public release.</li></ul>");
        }
    }
}
